services:
  redis:
    image: redis:7-alpine
    network_mode: host
    restart: unless-stopped

  bot_kevin:
    build: .
    network_mode: host
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      CONFIG_FILE: config_kevin.yaml
    volumes:
      - ./:/app:ro

  bot_saul:
    build: .
    network_mode: host
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      CONFIG_FILE: config_saul.yaml
    volumes:
      - ./:/app:ro

  bot_katherine:
    build: .
    network_mode: host
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      CONFIG_FILE: config_katherine.yaml
    volumes:
      - ./:/app:ro

  bot_damon:
    build: .
    network_mode: host
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      CONFIG_FILE: config_damon.yaml
    volumes:
      - ./:/app:ro

  bot_sarah:
    build: .
    network_mode: host
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      CONFIG_FILE: config_sarah.yaml
    volumes:
      - ./:/app:ro
